### ISSUE TITLE
Clingcon error: ast 'comment' does not have attribute 'body'

### ISSUE THREAD

**Issue by a1880** [potassco/flatzingo#47]
I am trying to run _flatzingo_ under Windows.

For even the smallest MiniZinc examples, I am getting the following _clingcon_ error:

`*** ERROR: (clingcon): ast 'comment' does not have attribute 'body'`

Any ideas what could cause this?

**Comment by MaxOstrowski** [comment]
I must admit that I'm a bit confused by this error. Could you provide the version number/way of installation of flatzingo/clingcon/minizinc and the command line including the example file that triggers this error for you ? Thank you very much.

**Comment by MaxOstrowski** [comment]
This seems to be a clingcon incompatibility with the newest clingo library. We are investigating it and get back to you. Thanks for the report.

**Comment by a1880** [comment]
The versions:
```
Python38
clingo-5.7.0
clingcon-5.2.1
flatzingo (current GitHub version)

```
The call of flatzingo (I had to modify the Python file and add ".exe" for the executables called):

```
K:\AK\Tools\flatzingo>python.exe K:\AK\Tools\flatzingo/fzn-flatzingo.py out.fzn
clingcon_command: ['clingcon.exe', 'K:\\AK\\Tools\\flatzingo\\encodings\\encoding.lp', 'K:\\AK\\Tools\\flatzingo\\encodings\\types.lp', '-t1', '--fast-exit', '--single-shot', '--translate-opt=10000', '--verbose=5', 'c:\\ak\\Temp\\tmpjve2zwoy\\test']
*** ERROR: (clingcon): ast 'comment' does not have attribute 'body'

```

Minimalistic MiniZinc input (no constraints; bigger examples exhibit the same behaviour):

`solve  satisfy;`

MiniZinc FlatZinc file:

`solve  satisfy;`

.lp file created by fzn2lp:

`solve(satisfy).`

**Comment by MaxOstrowski** [comment]
This was a bug in the underlying clingo system. Reinstalling clingcon with the newest version (wip from GitHub or potassco/label/dev from anaconda) should fix your problem. Feel free to open this thread again if you encounter any other problems.

**Comment by a1880** [comment]
Thank you for the instant fix.

I could not use it under Windows. Anaconda does not provide the latest WIP binaries.

I have installed/compiled the Linux binaries under Windows WSL2. This works ok.
From the MiniZinc IDE, I can't use Flatzingo. There is some mismatch in the output format.

Is it on purpose, that the flatzingo solver is restricted to a single thread?
I changed the solver configuration to multi-threading by adding "-p" as extraFlag.
This appears to be working ok.

**Comment by MaxOstrowski** [comment]
I can see the conda files for windows here. Isn't this the right stuff ?
https://anaconda.org/potassco/clingcon/files
You need to use the channel "potassco/label/dev/ to access the wip version. Also I think manually removing clingo from conda first help conda to pick up the latest version.

> From the MiniZinc IDE, I can't use Flatzingo. There is some mismatch in the output format.

I never used the IDE before, could you maybe provide some error message so that I can look into it ? The output format should hopefully be up to spec.

> Is it on purpose, that the flatzingo solver is restricted to a single thread?

No, flatzingo should natively support the option `-p` to set the number of threads.
This was a missing option in the minizinc configuration file. I updated the repository, so if you update and reinstall install.sh option -p should work.
